version: '3.1'

services:
  bot:
    container_name: parser_vk_tg_bot
    build:
      context: bot
      dockerfile: Dockerfile
    volumes:
      - ./bot/bot/db/logs_data/:/bot/db/logs_data/
    restart: always
    ports:
      - "3333:3333"
    networks:
      - botnet
    depends_on:
      - db

#  proxy:
#    container_name: nginx_proxy
#    build:
#      context: nginx
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - "443:443"
#      - "4444:4444"
#    networks:
#      - botnet
#    depends_on:
#      - bot

  api:
    container_name: api
    build:
      context: logs_api
      dockerfile: Dockerfile
    volumes:
      - ./bot/bot/db/logs_data/:/logs_data/
    restart: always
    ports:
      - "3003:3003"
    networks:
      - botnet
    depends_on:
      - bot

  db:
    container_name: postgres
    env_file:
      - ./postgresql/pg.env
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3232:3232'
    volumes:
      - ./postgresql/data/:/var/lib/postgresql/data/
    command:
    - 'postgres'
    - '-c'
    - 'config_file=/var/lib/PostgresConfig/postgresql.conf'
    networks:
      - botnet

networks:
  botnet:
    driver: bridge
