version: '3.1'

services:
#  bot:
#    container_name: bot_mk_2
#    build:
#      context: bot_1
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - "3333:3333"
#    networks:
#      - botnet
#    depends_on:
#      - db

#  proxy:
#    container_name: nginx_proxy
#    build:
#      context: nginx
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - "443:443"
#      - "4444:4444"
#    networks:
#      - botnet
#    depends_on:
#      - bot

  db:
    container_name: postgres
    env_file:
      - ./postgresql/pg.env
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3232:3232'
    volumes:
      - ./postgresql/data/:/var/lib/postgresql/data/
    command:
    - 'postgres'
    - '-c'
    - 'config_file=/var/lib/PostgresConfig/postgresql.conf'
    networks:
      - botnet

networks:
  botnet:
    driver: bridge
